#!/bin/bash

BASE='/opt/pixelpals/'
VENV_PYTHON=${BASE}'venv/bin/python'
MODULE='ppserver.celery'
LOG=${BASE}'logs/Celery.log'
CELERY=${BASE}'venv/bin/celery'

start() {
    cd ${BASE}
    nohup ${VENV_PYTHON} ${CELERY} -A ${MODULE} worker --logfile ${LOG} 2>&1 /dev/null &
}

status() {
    ps -ef | grep '/opt/pixelpals/venv/bin/celery'
}

case "$1" in
  start)
    start
    ;;
  status)
    status
    ;;
  *)
    echo "Usage: $0 {start}"
esac
