#!/bin/bash

BASE='/opt/pixelpals/'
VENV_PYTHON=${BASE}'venv/bin/python'
SCRIPT='single/pixel_pal_runner.py'
LOG=${BASE}'logs/PixelPalRunner.log'
URL='https://192.168.1.11/pixel/checkin'

start() {
    cd ${BASE}
    ${VENV_PYTHON} ${BASE}${SCRIPT} --host-name=`/bin/hostname` --log-file=${LOG} --url-checkin='https://192.168.1.11/pixel/checkin'
    return 0
}


case "$1" in
  start)
    start
    ;;
  *)
    echo "Usage: $0 {start}"
esac
